import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';

import 'daos/app_settings_dao.dart';
import 'daos/haul_dao.dart';
import 'daos/imported_dataset_dao.dart';
import 'daos/log_book_dao.dart';
import 'daos/marker_dao.dart';
import 'daos/offline_region_dao.dart';
import 'daos/track_point_dao.dart';
import 'daos/trip_dao.dart';
import 'daos/user_profile_dao.dart';
import 'tables.dart';

export 'daos/app_settings_dao.dart';
export 'daos/haul_dao.dart';
export 'daos/imported_dataset_dao.dart';
export 'daos/log_book_dao.dart';
export 'daos/marker_dao.dart';
export 'daos/offline_region_dao.dart';
export 'daos/track_point_dao.dart';
export 'daos/trip_dao.dart';
export 'daos/user_profile_dao.dart';
// Re-export tables + DAOs so that repository files can import a single
// barrel (app_database.dart) and get every type they need:
//   - DAO classes (HaulDao, TripDao, …) live in the dao files below.
//   - Row classes (HaulRow, TripRow, …) and Companion classes
//     (HaulsCompanion, …) are generated by Drift into
//     `app_database.g.dart` (included via the `part` directive).
// Without these `export`s, repository files that import only
// `app_database.dart` fail to compile with
// "Type 'HaulDao' not found" / "Type 'HaulRow' not found".
export 'tables.dart';

part 'app_database.g.dart';

/// The single Drift database for Langgeng Sea.
///
/// Local-only (per PRD §11 / NFR-05). Backed by a SQLite file in the
/// app's documents directory. Schema version bumps must ship a migration
/// in [MigrationStrategy.onUpgrade].
@DriftDatabase(
  tables: [
    Trips,
    Hauls,
    TrackPoints,
    OfflineRegions,
    LogBookEntries,
    CatchItems,
    Markers,
    UserProfiles,
    AppSettingsTable,
    ImportedDatasetsTable,
  ],
  daos: [
    TripDao,
    HaulDao,
    TrackPointDao,
    OfflineRegionDao,
    LogBookDao,
    MarkerDao,
    UserProfileDao,
    AppSettingsDao,
    ImportedDatasetDao,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test-only constructor that uses an in-memory SQLite.
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 10;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          // Help the GPS write path — most reads are per-haul time series.
          await customStatement(
            'CREATE INDEX IF NOT EXISTS idx_track_points_haul_ts '
            'ON track_points (haul_id, timestamp)',
          );
          await customStatement(
            'CREATE INDEX IF NOT EXISTS idx_hauls_trip_order '
            'ON hauls (trip_id, order_index)',
          );
          // Seed the app_settings singleton so reads never hit null.
          await _seedAppSettings();
        },
        onUpgrade: (m, from, to) async {
          // v1 → v2 adds the offline_regions table (M4). No data in the
          // old schema needs transformation.
          if (from < 2) {
            await m.createTable(offlineRegions);
          }
          // v2 → v3 adds log_book_entries, catch_items, markers (M5).
          if (from < 3) {
            await m.createTable(logBookEntries);
            await m.createTable(catchItems);
            await m.createTable(markers);
          }
          // v3 → v4 adds user_profiles (M8 onboarding).
          if (from < 4) {
            await m.createTable(userProfiles);
          }
          // v4 → v5 adds hauls.color_value for per-haul user colours
          // (Commit 2 history/map integration).
          if (from < 5) {
            await m.addColumn(hauls, hauls.colorValue);
          }
          // v5 → v6 adds app_settings (M11 navigation). Single-row
          // preferences table seeded with alarm sound + vibrate both
          // ON so existing users get sensible defaults without any UI
          // prompt. Spec calls this "v4 → v5" from the planning doc
          // perspective; in actual codebase it lands at 6 because the
          // colour-picker migration took v5 first.
          if (from < 6) {
            await m.createTable(appSettingsTable);
            await _seedAppSettings();
          }
          // v6 → v7 adds trips.color_value (PR #21 — per-Trip
          // polyline colour). Mirrors the earlier v4→v5 migration
          // that added hauls.color_value; existing trips keep
          // colour_value = NULL which falls back to the order-index
          // palette via AppColors.resolveHaulColor.
          if (from < 7) {
            await m.addColumn(trips, trips.colorValue);
          }
          // v7 → v8 adds app_settings.polyline_width for user-configurable
          // polyline thickness on map. Default 10px.
          if (from < 8) {
            await m.addColumn(appSettingsTable, appSettingsTable.polylineWidth);
          }
          // v8 → v9 adds app_settings.tracking_mode for the Mode
          // Tracking toggle (PR #29). Default 'normal' so existing
          // users — and freshly-migrated DBs — start without any
          // permission dialog firing on the next "MULAI" tap.
          if (from < 9) {
            await m.addColumn(appSettingsTable, appSettingsTable.trackingMode);
          }
          // v9 → v10 menambah dataset support (PR #33):
          // - Tabel `imported_datasets` untuk track satu file GPX
          //   sebagai satu dataset dengan metadata exporter +
          //   counter denormalized.
          // - Kolom `dataset_id TEXT NULL` di markers, trips, hauls
          //   sebagai FK soft (constraint enforce di repo, bukan SQL,
          //   karena Drift addColumn tidak support FK clause langsung).
          // Existing rows dapat NULL = "data milik user sendiri".
          if (from < 10) {
            await m.createTable(importedDatasetsTable);
            await m.addColumn(markers, markers.datasetId);
            await m.addColumn(trips, trips.datasetId);
            await m.addColumn(hauls, hauls.datasetId);
          }
        },
      );

  /// Insert the singleton app_settings row if the table is empty.
  /// Used by both `onCreate` (fresh install) and `onUpgrade v5→v6`
  /// (existing user upgrading). INSERT OR IGNORE keeps it idempotent
  /// so re-running the migration on a partially-upgraded DB can't
  /// double-seed.
  Future<void> _seedAppSettings() async {
    await customStatement(
      'INSERT OR IGNORE INTO app_settings '
      '(id, alarm_sound_enabled, alarm_vibrate_enabled, updated_at) '
      'VALUES (1, 1, 1, ?)',
      [DateTime.now().millisecondsSinceEpoch],
    );
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'langgeng_sea.sqlite'));

    // Android workaround: some OEMs' build of SQLite is too old.
    if (Platform.isAndroid) {
      await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    }
    return NativeDatabase.createInBackground(file, logStatements: false);
  });
}

/// Process-wide singleton so DAOs can be looked up from anywhere.
final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final db = AppDatabase();
  ref.onDispose(db.close);
  return db;
});
