name: langgeng_sea
description: "Aplikasi tracking GPS offline untuk nelayan trawl Indonesia."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  fl_chart: ^0.68.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.7

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^9.1.0

  # Location & GPS
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_local_notifications: ^17.2.3

  # Database
  drift: ^2.20.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # Models & serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.2

  # Files & sharing
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  xml: ^6.5.0

  # Utils
  intl: ^0.19.0
  collection: ^1.18.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

  # Code generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.20.2
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
